//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CApplication", Namespace="http://tempuri.org/")]
    public partial class CApplication : object
    {
        
        private int IdField;
        
        private string UniqueIdentifierField;
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UniqueIdentifier
        {
            get
            {
                return this.UniqueIdentifierField;
            }
            set
            {
                this.UniqueIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfFloat", Namespace="http://tempuri.org/", ItemName="float")]
    public class ArrayOfFloat : System.Collections.Generic.List<float>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAuditTrial", Namespace="http://tempuri.org/")]
    public partial class CAuditTrial : object
    {
        
        private string ModuleCodeField;
        
        private string UserGuidField;
        
        private string OldValueField;
        
        private string NewValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ModuleCode
        {
            get
            {
                return this.ModuleCodeField;
            }
            set
            {
                this.ModuleCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OldValue
        {
            get
            {
                return this.OldValueField;
            }
            set
            {
                this.OldValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewValue
        {
            get
            {
                return this.NewValueField;
            }
            set
            {
                this.NewValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationStatus", Namespace="http://tempuri.org/")]
    public enum AuthenticationStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessGranted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoApplicationAccess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserOrPassword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OUser", Namespace="http://tempuri.org/")]
    public partial class OUser : object
    {
        
        private string UserGuidField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ECXSecurityAccessSoap")]
    public interface ECXSecurityAccessSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActiveApplications", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.GetActiveApplicationsResponse> GetActiveApplicationsAsync(ServiceReference2.GetActiveApplicationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasRight", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.HasRightResponse> HasRightAsync(ServiceReference2.HasRightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasRights", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.HasRightsResponse> HasRightsAsync(ServiceReference2.HasRightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserHasApplicationAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.UserHasApplicationAccessResponse> UserHasApplicationAccessAsync(ServiceReference2.UserHasApplicationAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserHasApplicationsAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.UserHasApplicationsAccessResponse> UserHasApplicationsAccessAsync(ServiceReference2.UserHasApplicationsAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAuditTrail", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.AddAuditTrailResponse> AddAuditTrailAsync(ServiceReference2.AddAuditTrailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAuditTrails", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.AddAuditTrailsResponse> AddAuditTrailsAsync(ServiceReference2.AddAuditTrailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuditTrailCommit", ReplyAction="*")]
        System.Threading.Tasks.Task AuditTrailCommitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuditTrailRollback", ReplyAction="*")]
        System.Threading.Tasks.Task AuditTrailRollbackAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuthenticated", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.IsAuthenticatedResponse> IsAuthenticatedAsync(ServiceReference2.IsAuthenticatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserHasLocationAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.UserHasLocationAccessResponse> UserHasLocationAccessAsync(ServiceReference2.UserHasLocationAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsersWithRight", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.UsersWithRightResponse> UsersWithRightAsync(ServiceReference2.UsersWithRightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.GetUserNameResponse> GetUserNameAsync(ServiceReference2.GetUserNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveApplicationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveApplications", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.GetActiveApplicationsRequestBody Body;
        
        public GetActiveApplicationsRequest()
        {
        }
        
        public GetActiveApplicationsRequest(ServiceReference2.GetActiveApplicationsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetActiveApplicationsRequestBody
    {
        
        public GetActiveApplicationsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveApplicationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveApplicationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.GetActiveApplicationsResponseBody Body;
        
        public GetActiveApplicationsResponse()
        {
        }
        
        public GetActiveApplicationsResponse(ServiceReference2.GetActiveApplicationsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActiveApplicationsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.CApplication[] GetActiveApplicationsResult;
        
        public GetActiveApplicationsResponseBody()
        {
        }
        
        public GetActiveApplicationsResponseBody(ServiceReference2.CApplication[] GetActiveApplicationsResult)
        {
            this.GetActiveApplicationsResult = GetActiveApplicationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRight", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.HasRightRequestBody Body;
        
        public HasRightRequest()
        {
        }
        
        public HasRightRequest(ServiceReference2.HasRightRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocationCode;
        
        public HasRightRequestBody()
        {
        }
        
        public HasRightRequestBody(string UserGuid, string Code, string LocationCode)
        {
            this.UserGuid = UserGuid;
            this.Code = Code;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.HasRightResponseBody Body;
        
        public HasRightResponse()
        {
        }
        
        public HasRightResponse(ServiceReference2.HasRightResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float HasRightResult;
        
        public HasRightResponseBody()
        {
        }
        
        public HasRightResponseBody(float HasRightResult)
        {
            this.HasRightResult = HasRightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRights", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.HasRightsRequestBody Body;
        
        public HasRightsRequest()
        {
        }
        
        public HasRightsRequest(ServiceReference2.HasRightsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference2.ArrayOfString Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocationCode;
        
        public HasRightsRequestBody()
        {
        }
        
        public HasRightsRequestBody(string UserGuid, ServiceReference2.ArrayOfString Code, string LocationCode)
        {
            this.UserGuid = UserGuid;
            this.Code = Code;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasRightsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasRightsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.HasRightsResponseBody Body;
        
        public HasRightsResponse()
        {
        }
        
        public HasRightsResponse(ServiceReference2.HasRightsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasRightsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ArrayOfFloat HasRightsResult;
        
        public HasRightsResponseBody()
        {
        }
        
        public HasRightsResponseBody(ServiceReference2.ArrayOfFloat HasRightsResult)
        {
            this.HasRightsResult = HasRightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationAccessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationAccess", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UserHasApplicationAccessRequestBody Body;
        
        public UserHasApplicationAccessRequest()
        {
        }
        
        public UserHasApplicationAccessRequest(ServiceReference2.UserHasApplicationAccessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationAccessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApplicationCode;
        
        public UserHasApplicationAccessRequestBody()
        {
        }
        
        public UserHasApplicationAccessRequestBody(string UserGuid, string ApplicationCode)
        {
            this.UserGuid = UserGuid;
            this.ApplicationCode = ApplicationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationAccessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationAccessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UserHasApplicationAccessResponseBody Body;
        
        public UserHasApplicationAccessResponse()
        {
        }
        
        public UserHasApplicationAccessResponse(ServiceReference2.UserHasApplicationAccessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationAccessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserHasApplicationAccessResult;
        
        public UserHasApplicationAccessResponseBody()
        {
        }
        
        public UserHasApplicationAccessResponseBody(bool UserHasApplicationAccessResult)
        {
            this.UserHasApplicationAccessResult = UserHasApplicationAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationsAccessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationsAccess", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UserHasApplicationsAccessRequestBody Body;
        
        public UserHasApplicationsAccessRequest()
        {
        }
        
        public UserHasApplicationsAccessRequest(ServiceReference2.UserHasApplicationsAccessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationsAccessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference2.ArrayOfString ApplicationCode;
        
        public UserHasApplicationsAccessRequestBody()
        {
        }
        
        public UserHasApplicationsAccessRequestBody(string UserGuid, ServiceReference2.ArrayOfString ApplicationCode)
        {
            this.UserGuid = UserGuid;
            this.ApplicationCode = ApplicationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasApplicationsAccessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasApplicationsAccessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UserHasApplicationsAccessResponseBody Body;
        
        public UserHasApplicationsAccessResponse()
        {
        }
        
        public UserHasApplicationsAccessResponse(ServiceReference2.UserHasApplicationsAccessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasApplicationsAccessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ArrayOfBoolean UserHasApplicationsAccessResult;
        
        public UserHasApplicationsAccessResponseBody()
        {
        }
        
        public UserHasApplicationsAccessResponseBody(ServiceReference2.ArrayOfBoolean UserHasApplicationsAccessResult)
        {
            this.UserHasApplicationsAccessResult = UserHasApplicationsAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrail", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.AddAuditTrailRequestBody Body;
        
        public AddAuditTrailRequest()
        {
        }
        
        public AddAuditTrailRequest(ServiceReference2.AddAuditTrailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModuleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OldValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewValue;
        
        public AddAuditTrailRequestBody()
        {
        }
        
        public AddAuditTrailRequestBody(string ModuleCode, string UserGuid, string OldValue, string NewValue)
        {
            this.ModuleCode = ModuleCode;
            this.UserGuid = UserGuid;
            this.OldValue = OldValue;
            this.NewValue = NewValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.AddAuditTrailResponseBody Body;
        
        public AddAuditTrailResponse()
        {
        }
        
        public AddAuditTrailResponse(ServiceReference2.AddAuditTrailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddAuditTrailResult;
        
        public AddAuditTrailResponseBody()
        {
        }
        
        public AddAuditTrailResponseBody(bool AddAuditTrailResult)
        {
            this.AddAuditTrailResult = AddAuditTrailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrails", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.AddAuditTrailsRequestBody Body;
        
        public AddAuditTrailsRequest()
        {
        }
        
        public AddAuditTrailsRequest(ServiceReference2.AddAuditTrailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.CAuditTrial[] AuditTrialList;
        
        public AddAuditTrailsRequestBody()
        {
        }
        
        public AddAuditTrailsRequestBody(ServiceReference2.CAuditTrial[] AuditTrialList)
        {
            this.AuditTrialList = AuditTrialList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAuditTrailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAuditTrailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.AddAuditTrailsResponseBody Body;
        
        public AddAuditTrailsResponse()
        {
        }
        
        public AddAuditTrailsResponse(ServiceReference2.AddAuditTrailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAuditTrailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddAuditTrailsResult;
        
        public AddAuditTrailsResponseBody()
        {
        }
        
        public AddAuditTrailsResponseBody(bool AddAuditTrailsResult)
        {
            this.AddAuditTrailsResult = AddAuditTrailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticated", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.IsAuthenticatedRequestBody Body;
        
        public IsAuthenticatedRequest()
        {
        }
        
        public IsAuthenticatedRequest(ServiceReference2.IsAuthenticatedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApplicationCode;
        
        public IsAuthenticatedRequestBody()
        {
        }
        
        public IsAuthenticatedRequestBody(string username, string Password, string ApplicationCode)
        {
            this.username = username;
            this.Password = Password;
            this.ApplicationCode = ApplicationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticatedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.IsAuthenticatedResponseBody Body;
        
        public IsAuthenticatedResponse()
        {
        }
        
        public IsAuthenticatedResponse(ServiceReference2.IsAuthenticatedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ServiceReference2.AuthenticationStatus IsAuthenticatedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserGuid;
        
        public IsAuthenticatedResponseBody()
        {
        }
        
        public IsAuthenticatedResponseBody(ServiceReference2.AuthenticationStatus IsAuthenticatedResult, string UserGuid)
        {
            this.IsAuthenticatedResult = IsAuthenticatedResult;
            this.UserGuid = UserGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasLocationAccessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasLocationAccess", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UserHasLocationAccessRequestBody Body;
        
        public UserHasLocationAccessRequest()
        {
        }
        
        public UserHasLocationAccessRequest(ServiceReference2.UserHasLocationAccessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasLocationAccessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LocationCode;
        
        public UserHasLocationAccessRequestBody()
        {
        }
        
        public UserHasLocationAccessRequestBody(string UserGuid, string LocationCode)
        {
            this.UserGuid = UserGuid;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasLocationAccessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasLocationAccessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UserHasLocationAccessResponseBody Body;
        
        public UserHasLocationAccessResponse()
        {
        }
        
        public UserHasLocationAccessResponse(ServiceReference2.UserHasLocationAccessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserHasLocationAccessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserHasLocationAccessResult;
        
        public UserHasLocationAccessResponseBody()
        {
        }
        
        public UserHasLocationAccessResponseBody(bool UserHasLocationAccessResult)
        {
            this.UserHasLocationAccessResult = UserHasLocationAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersWithRightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersWithRight", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UsersWithRightRequestBody Body;
        
        public UsersWithRightRequest()
        {
        }
        
        public UsersWithRightRequest(ServiceReference2.UsersWithRightRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersWithRightRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LocationCode;
        
        public UsersWithRightRequestBody()
        {
        }
        
        public UsersWithRightRequestBody(string Code, string LocationCode)
        {
            this.Code = Code;
            this.LocationCode = LocationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersWithRightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersWithRightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.UsersWithRightResponseBody Body;
        
        public UsersWithRightResponse()
        {
        }
        
        public UsersWithRightResponse(ServiceReference2.UsersWithRightResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersWithRightResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.OUser[] UsersWithRightResult;
        
        public UsersWithRightResponseBody()
        {
        }
        
        public UsersWithRightResponseBody(ServiceReference2.OUser[] UsersWithRightResult)
        {
            this.UsersWithRightResult = UsersWithRightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.GetUserNameRequestBody Body;
        
        public GetUserNameRequest()
        {
        }
        
        public GetUserNameRequest(ServiceReference2.GetUserNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public GetUserNameRequestBody()
        {
        }
        
        public GetUserNameRequestBody(string Id)
        {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference2.GetUserNameResponseBody Body;
        
        public GetUserNameResponse()
        {
        }
        
        public GetUserNameResponse(ServiceReference2.GetUserNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserNameResult;
        
        public GetUserNameResponseBody()
        {
        }
        
        public GetUserNameResponseBody(string GetUserNameResult)
        {
            this.GetUserNameResult = GetUserNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ECXSecurityAccessSoapChannel : ServiceReference2.ECXSecurityAccessSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ECXSecurityAccessSoapClient : System.ServiceModel.ClientBase<ServiceReference2.ECXSecurityAccessSoap>, ServiceReference2.ECXSecurityAccessSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ECXSecurityAccessSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ECXSecurityAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), ECXSecurityAccessSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ECXSecurityAccessSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ECXSecurityAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ECXSecurityAccessSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ECXSecurityAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ECXSecurityAccessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.GetActiveApplicationsResponse> ServiceReference2.ECXSecurityAccessSoap.GetActiveApplicationsAsync(ServiceReference2.GetActiveApplicationsRequest request)
        {
            return base.Channel.GetActiveApplicationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetActiveApplicationsResponse> GetActiveApplicationsAsync()
        {
            ServiceReference2.GetActiveApplicationsRequest inValue = new ServiceReference2.GetActiveApplicationsRequest();
            inValue.Body = new ServiceReference2.GetActiveApplicationsRequestBody();
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).GetActiveApplicationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.HasRightResponse> ServiceReference2.ECXSecurityAccessSoap.HasRightAsync(ServiceReference2.HasRightRequest request)
        {
            return base.Channel.HasRightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.HasRightResponse> HasRightAsync(string UserGuid, string Code, string LocationCode)
        {
            ServiceReference2.HasRightRequest inValue = new ServiceReference2.HasRightRequest();
            inValue.Body = new ServiceReference2.HasRightRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.Code = Code;
            inValue.Body.LocationCode = LocationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).HasRightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.HasRightsResponse> ServiceReference2.ECXSecurityAccessSoap.HasRightsAsync(ServiceReference2.HasRightsRequest request)
        {
            return base.Channel.HasRightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.HasRightsResponse> HasRightsAsync(string UserGuid, ServiceReference2.ArrayOfString Code, string LocationCode)
        {
            ServiceReference2.HasRightsRequest inValue = new ServiceReference2.HasRightsRequest();
            inValue.Body = new ServiceReference2.HasRightsRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.Code = Code;
            inValue.Body.LocationCode = LocationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).HasRightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.UserHasApplicationAccessResponse> ServiceReference2.ECXSecurityAccessSoap.UserHasApplicationAccessAsync(ServiceReference2.UserHasApplicationAccessRequest request)
        {
            return base.Channel.UserHasApplicationAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.UserHasApplicationAccessResponse> UserHasApplicationAccessAsync(string UserGuid, string ApplicationCode)
        {
            ServiceReference2.UserHasApplicationAccessRequest inValue = new ServiceReference2.UserHasApplicationAccessRequest();
            inValue.Body = new ServiceReference2.UserHasApplicationAccessRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.ApplicationCode = ApplicationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).UserHasApplicationAccessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.UserHasApplicationsAccessResponse> ServiceReference2.ECXSecurityAccessSoap.UserHasApplicationsAccessAsync(ServiceReference2.UserHasApplicationsAccessRequest request)
        {
            return base.Channel.UserHasApplicationsAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.UserHasApplicationsAccessResponse> UserHasApplicationsAccessAsync(string UserGuid, ServiceReference2.ArrayOfString ApplicationCode)
        {
            ServiceReference2.UserHasApplicationsAccessRequest inValue = new ServiceReference2.UserHasApplicationsAccessRequest();
            inValue.Body = new ServiceReference2.UserHasApplicationsAccessRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.ApplicationCode = ApplicationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).UserHasApplicationsAccessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.AddAuditTrailResponse> ServiceReference2.ECXSecurityAccessSoap.AddAuditTrailAsync(ServiceReference2.AddAuditTrailRequest request)
        {
            return base.Channel.AddAuditTrailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.AddAuditTrailResponse> AddAuditTrailAsync(string ModuleCode, string UserGuid, string OldValue, string NewValue)
        {
            ServiceReference2.AddAuditTrailRequest inValue = new ServiceReference2.AddAuditTrailRequest();
            inValue.Body = new ServiceReference2.AddAuditTrailRequestBody();
            inValue.Body.ModuleCode = ModuleCode;
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.OldValue = OldValue;
            inValue.Body.NewValue = NewValue;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).AddAuditTrailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.AddAuditTrailsResponse> ServiceReference2.ECXSecurityAccessSoap.AddAuditTrailsAsync(ServiceReference2.AddAuditTrailsRequest request)
        {
            return base.Channel.AddAuditTrailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.AddAuditTrailsResponse> AddAuditTrailsAsync(ServiceReference2.CAuditTrial[] AuditTrialList)
        {
            ServiceReference2.AddAuditTrailsRequest inValue = new ServiceReference2.AddAuditTrailsRequest();
            inValue.Body = new ServiceReference2.AddAuditTrailsRequestBody();
            inValue.Body.AuditTrialList = AuditTrialList;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).AddAuditTrailsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task AuditTrailCommitAsync()
        {
            return base.Channel.AuditTrailCommitAsync();
        }
        
        public System.Threading.Tasks.Task AuditTrailRollbackAsync()
        {
            return base.Channel.AuditTrailRollbackAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.IsAuthenticatedResponse> ServiceReference2.ECXSecurityAccessSoap.IsAuthenticatedAsync(ServiceReference2.IsAuthenticatedRequest request)
        {
            return base.Channel.IsAuthenticatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.IsAuthenticatedResponse> IsAuthenticatedAsync(string username, string Password, string ApplicationCode)
        {
            ServiceReference2.IsAuthenticatedRequest inValue = new ServiceReference2.IsAuthenticatedRequest();
            inValue.Body = new ServiceReference2.IsAuthenticatedRequestBody();
            inValue.Body.username = username;
            inValue.Body.Password = Password;
            inValue.Body.ApplicationCode = ApplicationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).IsAuthenticatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.UserHasLocationAccessResponse> ServiceReference2.ECXSecurityAccessSoap.UserHasLocationAccessAsync(ServiceReference2.UserHasLocationAccessRequest request)
        {
            return base.Channel.UserHasLocationAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.UserHasLocationAccessResponse> UserHasLocationAccessAsync(string UserGuid, string LocationCode)
        {
            ServiceReference2.UserHasLocationAccessRequest inValue = new ServiceReference2.UserHasLocationAccessRequest();
            inValue.Body = new ServiceReference2.UserHasLocationAccessRequestBody();
            inValue.Body.UserGuid = UserGuid;
            inValue.Body.LocationCode = LocationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).UserHasLocationAccessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.UsersWithRightResponse> ServiceReference2.ECXSecurityAccessSoap.UsersWithRightAsync(ServiceReference2.UsersWithRightRequest request)
        {
            return base.Channel.UsersWithRightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.UsersWithRightResponse> UsersWithRightAsync(string Code, string LocationCode)
        {
            ServiceReference2.UsersWithRightRequest inValue = new ServiceReference2.UsersWithRightRequest();
            inValue.Body = new ServiceReference2.UsersWithRightRequestBody();
            inValue.Body.Code = Code;
            inValue.Body.LocationCode = LocationCode;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).UsersWithRightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.GetUserNameResponse> ServiceReference2.ECXSecurityAccessSoap.GetUserNameAsync(ServiceReference2.GetUserNameRequest request)
        {
            return base.Channel.GetUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetUserNameResponse> GetUserNameAsync(string Id)
        {
            ServiceReference2.GetUserNameRequest inValue = new ServiceReference2.GetUserNameRequest();
            inValue.Body = new ServiceReference2.GetUserNameRequestBody();
            inValue.Body.Id = Id;
            return ((ServiceReference2.ECXSecurityAccessSoap)(this)).GetUserNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.3.5.85:5555/ECXSecurityAccess.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ECXSecurityAccessSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.3.5.85:5555/ECXSecurityAccess.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ECXSecurityAccessSoap,
            
            ECXSecurityAccessSoap12,
        }
    }
}
